### ISSUE TITLE
Cannot convert Figma to UI Package

### ISSUE THREAD

**Issue by kobago** [googlecodelabs/relay-codelabs#1]
Thank you for writing Codelab.
An error occurred when importing a Figma design into an Android Studio project.
Please teach me the solution if you know.

### Environment
- OS: macOS Venture 13.6.1
- Chip: Apple M2 Pro
- Android Studio: Giraffe 2022.3.1 Patch 4
- Java Runtime: 17.0.6+0-17.0.6b829.9-10027231 aarch64

### Error
```
com.google.relay.androidstudio.plugin.importer.FigmaServiceException: Command:
/Users/goggle555/Library/Application Support/Google/AndroidStudio2022.3/plugins/relay_android_studio/bin/macos_x86_64/figma_to_adin

Stack Trace:
Severe: Failed to transform https://www.figma.com/file/*****/ReflectDesign?type=design&t=CR8gWzNh66NgiP9t-6:

type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      _$VectorNodeFromJson (package:figma_to_adin/src/figmarest.g.dart:611)
#1      new VectorNode.fromJson (package:figma_to_adin/src/figmarest.dart:861)
#2      ContainerNode._childFromJson (package:figma_to_adin/src/figmarest.dart:449)
#3      ContainerNode.childrenFromJson (package:figma_to_adin/src/figmarest.dart:463)
#4      _$FrameNodeFromJson (package:figma_to_adin/src/figmarest.g.dart:455)
#5      new FrameNode.fromJson (package:figma_to_adin/src/figmarest.dart:759)
#6      ContainerNode._childFromJson (package:figma_to_adin/src/figmarest.dart:442)
#7      ContainerNode.childrenFromJson (package:figma_to_adin/src/figmarest.dart:463)
#8      _$FrameNodeFromJson (package:figma_to_adin/src/figmarest.g.dart:455)
#9      new FrameNode.fromJson (package:figma_to_adin/src/figmarest.dart:759)
#10     FigmaRestDataResolver._resolveFrom (package:figma_to_adin/src/figma_data.dart:339)
#11     FigmaRestDataResolver.resolveAll (package:figma_to_adin/src/figma_data.dart:309)
<asynchronous suspension>
#12     resolveUIPackagesSet (package:figma_to_adin/src/figma_resolver.dart:45)
<asynchronous suspension>
#13     main (file:///Volumes/BuildData/tmpfs/src/git/relay/figma_to_adin/bin/figma_to_adin.dart:120)
<asynchronous suspension>


	at com.google.relay.androidstudio.plugin.importer.FigmaService.importFile(FigmaService.kt:288)
	at com.google.relay.androidstudio.plugin.importer.FigmaService.importPackagesToTemp(FigmaService.kt:143)
	at com.google.relay.androidstudio.plugin.importer.FigmaImportWorker.doInBackground(FigmaImportWorker.java:89)
	at com.google.relay.androidstudio.plugin.importer.FigmaImportWorker.doInBackground(FigmaImportWorker.java:44)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by krisgiesing** [comment]
Thank you for submitting this error report! We have just released a hotfix to our Android Studio plugin (version 0.3.10-hotfix) that should fix this error.

**Comment by kobago** [comment]
@krisgiesing 
I was able to confirm that the import error has disappeared.
Thank you for fixing it :)
